### ISSUE TITLE
flog doesn't like <<~

### ISSUE THREAD

**Issue by joevandyk** [seattlerb/flog#63]
Maybe this is a ruby_parser or racc bug?

```
$ cat t1.rb
msg = <<~EOF
ack
EOF

$ flog t1.rb
ERROR: parsing ruby file t1.rb
ERROR! Aborting. You may want to run with --continue.
/usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/racc/parser.rb:528:in `on_error': t1.rb:1 :: parse error on value "<<" (tLSHFT) (Racc::ParseError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1163:in `on_error'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1075:in `block in process'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/local/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1063:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser.rb:31:in `block in process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser.rb:28:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ruby_parser-3.9.0/lib/ruby_parser.rb:28:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog.rb:222:in `flog_ruby!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog.rb:192:in `flog_ruby'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog.rb:180:in `block in flog'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog.rb:175:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog.rb:175:in `flog'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog_cli.rb:167:in `flog'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/lib/flog_cli.rb:25:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flog-4.6.1/bin/flog:5:in `<top (required)>'
	from /usr/local/bin/flog:22:in `load'
	from /usr/local/bin/flog:22:in `<main>'
```

**Comment by joevandyk** [comment]
Yeah, looks like a ruby_parser thing. https://github.com/seattlerb/ruby_parser/issues/218
