### ISSUE TITLE
undefined method `line' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by thrgamon** [seattlerb/flog#70]
Hi, 

I am running flog on a rails codebase and getting this error.

Any idea what might be going on?

Many thanks, 

Tom

```
$ flog
Traceback (most recent call last):
        23: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/bin/flog:25:in `<main>'
        22: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/bin/flog:25:in `load'
        21: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/bin/flog:5:in `<top (required)>'
        20: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog_cli.rb:28:in `run'
        19: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog_cli.rb:162:in `flog'
        18: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog.rb:177:in `flog'
        17: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog.rb:177:in `each'
        16: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog.rb:182:in `block in flog'
        15: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog.rb:194:in `flog_ruby'
        14: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/flog-4.6.4/lib/flog.rb:224:in `flog_ruby!'
        13: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser.rb:33:in `process'
        12: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser.rb:33:in `each'
        11: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser.rb:36:in `block in process'
        10: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser_extras.rb:1285:in `process'
         9: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
         8: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
         7: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
         6: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
         5: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
         4: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser_extras.rb:1297:in `block in process'
         3: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
         2: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
         1: from /Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby26_parser.rb:3651:in `_reduce_15'
/Users/tom.gamon/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ruby_parser-3.14.2/lib/ruby_parser_extras.rb:726:in `new_body': undefined method `line' for nil:NilClass (NoMethodError)
```

**Comment by zenspider** [comment]
This looks like it is happening before flog is even hit. A problem in ruby_parser instead. If you run with `-v` you should at least find the file causing the exception. Can you reduce to that and, if possible, please share? If you can't share the file, then you should be able to binary search the file (comment out half, then the other half, etc) to reduce the repro down to a small fragment that should be obfuscatable.

You should be able use ruby_parser's `ruby_parse_extract_error` to get it down to the method level... but if it isn't at the method level than it can fail.

**Comment by thrgamon** [comment]
Ah yep, I see that now. 

I will have a go at trying to narrowing it down, thanks for the steps. 

Will let you know what I find!

Tom

**Comment by thrgamon** [comment]
Hey @zenspider, I raised the issue here:

https://github.com/seattlerb/ruby_parser/issues/306

So I will follow it up with them, but I have found a workaround for now, so will close down this comment.

Thanks for pointing me on the right path!

Tom
