### ISSUE TITLE
Ruby 3.1. Not worked. undefined method `sexp_type' for nil:NilClass

### ISSUE THREAD

**Issue by prtngn** [seattlerb/flog#77]
rubycritic (4.7.0)
      flay (~> 2.8)
      flog (~> 4.4)

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.14

```
➜  telegram_sender git:(master) ✗ bundle exec flog
/Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:368:in `process_block_pass': undefined method `sexp_type' for nil:NilClass (NoMethodError)

    case arg.sexp_type
            ^^^^^^^^^^
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:272:in `block (2 levels) in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:327:in `error_handler'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:271:in `block in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:391:in `in_context'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:246:in `process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:695:in `process_until_empty'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:398:in `block in process_call'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:268:in `penalize_by'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:397:in `process_call'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:272:in `block (2 levels) in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:327:in `error_handler'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:271:in `block in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:391:in `in_context'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:246:in `process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:695:in `process_until_empty'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:649:in `block in process_defs'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:556:in `in_method'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:645:in `process_defs'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:272:in `block (2 levels) in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:327:in `error_handler'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:271:in `block in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:391:in `in_context'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:246:in `process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:695:in `process_until_empty'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:436:in `block in process_class'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:610:in `block in process_class'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:542:in `block in in_klass'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:713:in `with_new_method_stack'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:541:in `in_klass'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:608:in `process_class'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:432:in `process_class'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:272:in `block (2 levels) in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:327:in `error_handler'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:271:in `block in process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:391:in `in_context'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/sexp_processor-4.16.1/lib/sexp_processor.rb:246:in `process'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:230:in `flog_ruby!'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:195:in `flog_ruby'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:183:in `block in flog'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:178:in `each'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog.rb:178:in `flog'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog_cli.rb:162:in `flog'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/lib/flog_cli.rb:28:in `run'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/gems/flog-4.6.5/bin/flog:5:in `<top (required)>'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/bin/flog:25:in `load'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/bin/flog:25:in `<main>'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/bin/ruby_executable_hooks:22:in `eval'
        from /Users/prtngn/.rvm/gems/ruby-3.1.2@telegram_sender/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by TachoMex** [comment]
I think this bug is related to the new sugar in ruby 3. 

When you pass an anonymous block this error is triggered. For example:

```
def foo(a, b, &)
  bar(a, b, &)
end
``` 

You normally saw a `&block`  in those params, maybe flog is expecting a var after the `&`.

**Comment by zenspider** [comment]
This is fixed and will go out in the next release.
